<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_System_Model_Base_Addon extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Addon', $model);
        $this->_vars = array('id' => null, 'addon_name' => null, 'addon_version' => null, 'addon_params' => null, 'addon_priority' => 0, 'addon_events' => null, 'addon_parent_addon' => null, 'addon_created' => 0, 'addon_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'addon_name' => null, 'addon_created' => 0, 'addon_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('name');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['addon_name'];
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'name')
            return $this->_vars['addon_name'];
        elseif ($name === 'version')
            return $this->_vars['addon_version'];
        elseif ($name === 'params')
            return $this->_vars['addon_params'];
        elseif ($name === 'priority')
            return $this->_vars['addon_priority'];
        elseif ($name === 'events')
            return $this->_vars['addon_events'];
        elseif ($name === 'parent_addon')
            return $this->_vars['addon_parent_addon'];
        elseif ($name === 'created')
            return $this->_vars['addon_created'];
        elseif ($name === 'updated')
            return $this->_vars['addon_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'name')
            $this->_setVar('addon_name', $value);
        elseif ($name === 'version')
            $this->_setVar('addon_version', $value);
        elseif ($name === 'params')
            $this->_setVar('addon_params', $value);
        elseif ($name === 'priority')
            $this->_setVar('addon_priority', $value);
        elseif ($name === 'events')
            $this->_setVar('addon_events', $value);
        elseif ($name === 'parent_addon')
            $this->_setVar('addon_parent_addon', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'addon_priority')
            $this->_vars['addon_priority'] = (int)$value;
        elseif ($name === 'addon_events')
            $this->_vars['addon_events'] = @unserialize($value);
        elseif ($name === 'addon_created')
            $this->_vars['addon_created'] = (int)$value;
        elseif ($name === 'addon_updated')
            $this->_vars['addon_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_System_Model_Base_AddonRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Addon', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_System_Model_Base_AddonsByRowset($rs, $this->_model->create('Addon'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_System_Model_Base_Addons($this->_model, $entities);
    }
}

class Sabai_Addon_System_Model_Base_AddonsByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_System_Model_Addon $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Addons', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_System_Model_Base_Addons extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Addons', $entities);
    }
}