<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_System_Model_Base_AddonCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'addon_name',
        'version' => 'addon_version',
        'params' => 'addon_params',
        'priority' => 'addon_priority',
        'events' => 'addon_events',
        'parentAddon' => 'addon_parent_addon',
        'created' => 'addon_created',
        'updated' => 'addon_updated',
    );
}