<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_System_Model_Base_AdminrouteCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'path' => 'adminroute_path',
        'method' => 'adminroute_method',
        'format' => 'adminroute_format',
        'controller' => 'adminroute_controller',
        'controllerAddon' => 'adminroute_controller_addon',
        'forward' => 'adminroute_forward',
        'addon' => 'adminroute_addon',
        'type' => 'adminroute_type',
        'class' => 'adminroute_class',
        'accessCallback' => 'adminroute_access_callback',
        'titleCallback' => 'adminroute_title_callback',
        'callbackPath' => 'adminroute_callback_path',
        'callbackAddon' => 'adminroute_callback_addon',
        'title' => 'adminroute_title',
        'description' => 'adminroute_description',
        'weight' => 'adminroute_weight',
        'depth' => 'adminroute_depth',
        'ajax' => 'adminroute_ajax',
        'priority' => 'adminroute_priority',
        'data' => 'adminroute_data',
        'id' => 'adminroute_id',
        'created' => 'adminroute_created',
        'updated' => 'adminroute_updated',
    );
}