<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_System_Model_Base_Permission extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Permission', $model);
        $this->_vars = array('permission_name' => null, 'permission_title' => null, 'permission_addon' => null, 'permission_weight' => 0, 'permission_description' => null, 'permission_guest_allowed' => false, 'permission_permissioncategory_name' => null, 'permission_id' => 0, 'permission_created' => 0, 'permission_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('permission_id' => 0, 'permission_created' => 0, 'permission_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('name');
    }

    public function __get($name)
    {
        if ($name === 'name')
            return $this->_vars['permission_name'];
        elseif ($name === 'title')
            return $this->_vars['permission_title'];
        elseif ($name === 'addon')
            return $this->_vars['permission_addon'];
        elseif ($name === 'weight')
            return $this->_vars['permission_weight'];
        elseif ($name === 'description')
            return $this->_vars['permission_description'];
        elseif ($name === 'guest_allowed')
            return $this->_vars['permission_guest_allowed'];
        elseif ($name === 'permissioncategory_name')
            return $this->_vars['permission_permissioncategory_name'];
        elseif ($name === 'id')
            return $this->_vars['permission_id'];
        elseif ($name === 'created')
            return $this->_vars['permission_created'];
        elseif ($name === 'updated')
            return $this->_vars['permission_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'name')
            $this->_setVar('permission_name', $value);
        elseif ($name === 'title')
            $this->_setVar('permission_title', $value);
        elseif ($name === 'addon')
            $this->_setVar('permission_addon', $value);
        elseif ($name === 'weight')
            $this->_setVar('permission_weight', $value);
        elseif ($name === 'description')
            $this->_setVar('permission_description', $value);
        elseif ($name === 'guest_allowed')
            $this->_setVar('permission_guest_allowed', $value);
        elseif ($name === 'permissioncategory_name')
            $this->_setVar('permission_permissioncategory_name', $value);
        elseif ($name === 'id')
            $this->_setVar('permission_id', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'permission_weight')
            $this->_vars['permission_weight'] = (int)$value;
        elseif ($name === 'permission_guest_allowed')
            $this->_vars['permission_guest_allowed'] = (bool)$value;
        elseif ($name === 'permission_id')
            $this->_vars['permission_id'] = (int)$value;
        elseif ($name === 'permission_created')
            $this->_vars['permission_created'] = (int)$value;
        elseif ($name === 'permission_updated')
            $this->_vars['permission_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_System_Model_Base_PermissionRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Permission', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_System_Model_Base_PermissionsByRowset($rs, $this->_model->create('Permission'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_System_Model_Base_Permissions($this->_model, $entities);
    }
}

class Sabai_Addon_System_Model_Base_PermissionsByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_System_Model_Permission $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Permissions', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_System_Model_Base_Permissions extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Permissions', $entities);
    }
}