<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_System_Model_Base_PermissionCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'permission_name',
        'title' => 'permission_title',
        'addon' => 'permission_addon',
        'weight' => 'permission_weight',
        'description' => 'permission_description',
        'guestAllowed' => 'permission_guest_allowed',
        'permissioncategoryName' => 'permission_permissioncategory_name',
        'id' => 'permission_id',
        'created' => 'permission_created',
        'updated' => 'permission_updated',
    );
}