<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_System_Model_Base_Role extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Role', $model);
        $this->_vars = array('id' => null, 'role_name' => null, 'role_title' => null, 'role_permissions' => null, 'role_created' => 0, 'role_updated' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('id' => null, 'role_name' => null, 'role_created' => 0, 'role_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return $this->__get('title');
    }

    public function initVars(array $arr)
    {
        parent::initVars($arr);
        $this->_vars['id'] = $this->_vars['role_name'];
    }

    public function __get($name)
    {
        if ($name === 'id')
            return $this->_vars['id'];
        elseif ($name === 'name')
            return $this->_vars['role_name'];
        elseif ($name === 'title')
            return $this->_vars['role_title'];
        elseif ($name === 'permissions')
            return $this->_vars['role_permissions'];
        elseif ($name === 'created')
            return $this->_vars['role_created'];
        elseif ($name === 'updated')
            return $this->_vars['role_updated'];
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'id')
            $this->_setVar('id', $value);
        elseif ($name === 'name')
            $this->_setVar('role_name', $value);
        elseif ($name === 'title')
            $this->_setVar('role_title', $value);
        elseif ($name === 'permissions')
            $this->_setVar('role_permissions', $value);
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'role_permissions')
            $this->_vars['role_permissions'] = @unserialize($value);
        elseif ($name === 'role_created')
            $this->_vars['role_created'] = (int)$value;
        elseif ($name === 'role_updated')
            $this->_vars['role_updated'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_System_Model_Base_RoleRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Role', $model);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_System_Model_Base_RolesByRowset($rs, $this->_model->create('Role'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_System_Model_Base_Roles($this->_model, $entities);
    }
}

class Sabai_Addon_System_Model_Base_RolesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_System_Model_Role $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Roles', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_System_Model_Base_Roles extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Roles', $entities);
    }
}