<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_System_Model_Base_RoleCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'role_name',
        'title' => 'role_title',
        'permissions' => 'role_permissions',
        'created' => 'role_created',
        'updated' => 'role_updated',
    );
}