<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_System_Model_Base_RouteCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'path' => 'route_path',
        'method' => 'route_method',
        'format' => 'route_format',
        'controller' => 'route_controller',
        'controllerAddon' => 'route_controller_addon',
        'forward' => 'route_forward',
        'addon' => 'route_addon',
        'type' => 'route_type',
        'class' => 'route_class',
        'accessCallback' => 'route_access_callback',
        'titleCallback' => 'route_title_callback',
        'callbackPath' => 'route_callback_path',
        'callbackAddon' => 'route_callback_addon',
        'title' => 'route_title',
        'description' => 'route_description',
        'weight' => 'route_weight',
        'depth' => 'route_depth',
        'ajax' => 'route_ajax',
        'priority' => 'route_priority',
        'data' => 'route_data',
        'id' => 'route_id',
        'created' => 'route_created',
        'updated' => 'route_updated',
    );
}