<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_File_Model_Base_FileCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'file_name',
        'title' => 'file_title',
        'type' => 'file_type',
        'size' => 'file_size',
        'extension' => 'file_extension',
        'hash' => 'file_hash',
        'isImage' => 'file_is_image',
        'width' => 'file_width',
        'height' => 'file_height',
        'id' => 'file_id',
        'created' => 'file_created',
        'updated' => 'file_updated',
        'tokenId' => 'file_token_id',
        'userId' => 'file_user_id',
    );
}