<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_File_Model_Base_TokenCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'hash' => 'token_hash',
        'formBuildId' => 'token_form_build_id',
        'formFieldName' => 'token_form_field_name',
        'expires' => 'token_expires',
        'settings' => 'token_settings',
        'fileCount' => 'token_file_count',
        'id' => 'token_id',
        'created' => 'token_created',
        'updated' => 'token_updated',
        'userId' => 'token_user_id',
    );
}