<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Comment_Model_Base_PostCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'body' => 'post_body',
        'bodyHtml' => 'post_body_html',
        'entityId' => 'post_entity_id',
        'entityBundleId' => 'post_entity_bundle_id',
        'publishedAt' => 'post_published_at',
        'status' => 'post_status',
        'voteSum' => 'post_vote_sum',
        'voteCount' => 'post_vote_count',
        'flagSum' => 'post_flag_sum',
        'flagCount' => 'post_flag_count',
        'editCount' => 'post_edit_count',
        'editLastAt' => 'post_edit_last_at',
        'editLastBy' => 'post_edit_last_by',
        'editLastReason' => 'post_edit_last_reason',
        'hiddenAt' => 'post_hidden_at',
        'hiddenBy' => 'post_hidden_by',
        'voteDisabled' => 'post_vote_disabled',
        'flagDisabled' => 'post_flag_disabled',
        'id' => 'post_id',
        'created' => 'post_created',
        'updated' => 'post_updated',
        'userId' => 'post_user_id',
    );
}