<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Comment_Model_Base_VoteCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'value' => 'vote_value',
        'tag' => 'vote_tag',
        'id' => 'vote_id',
        'created' => 'vote_created',
        'updated' => 'vote_updated',
        'postId' => 'vote_post_id',
        'userId' => 'vote_user_id',
    );
}