<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Comment_Model_Base_Vote extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Vote', $model);
        $this->_vars = array('vote_value' => 0, 'vote_tag' => null, 'vote_id' => 0, 'vote_created' => 0, 'vote_updated' => 0, 'vote_post_id' => 0, 'vote_user_id' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('vote_id' => 0, 'vote_created' => 0, 'vote_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return 'Vote:' . $this->__get('id');
    }

    protected function _assignUser($user, $markDirty = true)
    {
        $this->_setVar('vote_user_id', $user->id, $markDirty);
    }

    protected function _fetchUser()
    {
        if (!isset($this->_objects['User'])) {
            $this->_objects['User'] = $this->_model->UserIdentity($this->_vars['vote_user_id']);
        }

        return $this->_objects['User'];
    }

    public function isOwnedBy($user)
    {
        return $this->user_id && $this->user_id == $user->id;
    }

    public function __get($name)
    {
        if ($name === 'value')
            return $this->_vars['vote_value'];
        elseif ($name === 'tag')
            return $this->_vars['vote_tag'];
        elseif ($name === 'id')
            return $this->_vars['vote_id'];
        elseif ($name === 'created')
            return $this->_vars['vote_created'];
        elseif ($name === 'updated')
            return $this->_vars['vote_updated'];
        elseif ($name === 'post_id')
            return $this->_vars['vote_post_id'];
        elseif ($name === 'user_id')
            return $this->_vars['vote_user_id'];
        elseif ($name === 'Post')
            return $this->_fetchEntity('Post', 'post_id');
        elseif ($name === 'User')
            return $this->_fetchUser();
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'value')
            $this->_setVar('vote_value', $value);
        elseif ($name === 'tag')
            $this->_setVar('vote_tag', $value);
        elseif ($name === 'id')
            $this->_setVar('vote_id', $value);
        elseif ($name === 'user_id')
            $this->_setVar('vote_user_id', $value);
        elseif ($name === 'User')
            $this->_assignUser($value);
        elseif ($name === 'post_id')
            $this->_assignEntityById('Post', $value, 'vote_post_id');
        elseif ($name === 'Post') {
            $_value = is_array($value) ? $value[0] : $value;
            if (is_object($_value)) {
                $this->_assignEntity($_value, 'vote_post_id');
            } else {
                $this->_assignEntityById('Post', $_value, 'vote_post_id');
            }
        }
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'vote_value')
            $this->_vars['vote_value'] = (int)$value;
        elseif ($name === 'vote_id')
            $this->_vars['vote_id'] = (int)$value;
        elseif ($name === 'vote_created')
            $this->_vars['vote_created'] = (int)$value;
        elseif ($name === 'vote_updated')
            $this->_vars['vote_updated'] = (int)$value;
        elseif ($name === 'vote_post_id')
            $this->_vars['vote_post_id'] = (int)$value;
        elseif ($name === 'vote_user_id')
            $this->_vars['vote_user_id'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_Comment_Model_Base_VoteRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('Vote', $model);
    }

    public function fetchByUser($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('vote_user_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByUser($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('User', $id, $perpage, $sort, $order);
    }

    public function countByUser($id)
    {
        return $this->_countByForeign('vote_user_id', $id);
    }

    public function fetchByUserAndCriteria($id, SabaiFramework_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('vote_user_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByUserAndCriteria($id, SabaiFramework_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('User', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByUserAndCriteria($id, SabaiFramework_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('vote_user_id', $id, $criteria);
    }

    public function fetchByPost($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('vote_post_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByPost($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('Post', $id, $perpage, $sort, $order);
    }

    public function countByPost($id)
    {
        return $this->_countByForeign('vote_post_id', $id);
    }

    public function fetchByPostAndCriteria($id, SabaiFramework_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('vote_post_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByPostAndCriteria($id, SabaiFramework_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('Post', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByPostAndCriteria($id, SabaiFramework_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('vote_post_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_Comment_Model_Base_VotesByRowset($rs, $this->_model->create('Vote'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_Comment_Model_Base_Votes($this->_model, $entities);
    }
}

class Sabai_Addon_Comment_Model_Base_VotesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_Comment_Model_Vote $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('Votes', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_Comment_Model_Base_Votes extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Votes', $entities);
    }
}