<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Content_Model_Base_PostCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'title' => 'post_title',
        'slug' => 'post_slug',
        'published' => 'post_published',
        'status' => 'post_status',
        'views' => 'post_views',
        'entityBundleName' => 'post_entity_bundle_name',
        'entityBundleType' => 'post_entity_bundle_type',
        'id' => 'post_id',
        'created' => 'post_created',
        'updated' => 'post_updated',
        'userId' => 'post_user_id',
    );
}