<?php
class Sabai_Addon_System_Model_Reputation extends Sabai_Addon_System_Model_Base_Reputation
{
}

class Sabai_Addon_System_Model_ReputationRepository extends Sabai_Addon_System_Model_Base_ReputationRepository
{
}