<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Voting_Model_Base_VoteCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'entityType' => 'vote_entity_type',
        'bundleId' => 'vote_bundle_id',
        'entityId' => 'vote_entity_id',
        'value' => 'vote_value',
        'tag' => 'vote_tag',
        'name' => 'vote_name',
        'comment' => 'vote_comment',
        'referenceId' => 'vote_reference_id',
        'ip' => 'vote_ip',
        'id' => 'vote_id',
        'created' => 'vote_created',
        'updated' => 'vote_updated',
        'userId' => 'vote_user_id',
    );
}