<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Voting_Model_Base_VoteGateway extends SabaiFramework_Model_Gateway
{
    public function getName()
    {
        return 'voting_vote';
    }

    public function getFields()
    {
        return array('vote_entity_type' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'vote_bundle_id' => SabaiFramework_Model::KEY_TYPE_INT, 'vote_entity_id' => SabaiFramework_Model::KEY_TYPE_INT, 'vote_value' => SabaiFramework_Model::KEY_TYPE_DECIMAL, 'vote_tag' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'vote_name' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'vote_comment' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'vote_reference_id' => SabaiFramework_Model::KEY_TYPE_INT, 'vote_ip' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'vote_id' => SabaiFramework_Model::KEY_TYPE_INT, 'vote_created' => SabaiFramework_Model::KEY_TYPE_INT, 'vote_updated' => SabaiFramework_Model::KEY_TYPE_INT, 'vote_user_id' => SabaiFramework_Model::KEY_TYPE_INT);
    }

    protected function _getIdFieldName()
    {
        return 'vote_id';
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %svoting_vote WHERE vote_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %svoting_vote WHERE vote_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(', ', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$svoting_vote voting_vote WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery(&$values)
    {
        $values['vote_created'] = time();
        $values['vote_updated'] = 0;
        return sprintf('INSERT INTO %svoting_vote(vote_entity_type, vote_bundle_id, vote_entity_id, vote_value, vote_tag, vote_name, vote_comment, vote_reference_id, vote_ip, vote_id, vote_created, vote_updated, vote_user_id) VALUES(%s, %d, %d, %F, %s, %s, %s, %d, %s, %s, %d, %d, %d)', $this->_db->getResourcePrefix(), $this->_db->escapeString($values['vote_entity_type']), $values['vote_bundle_id'], $values['vote_entity_id'], $values['vote_value'], $this->_db->escapeString($values['vote_tag']), $this->_db->escapeString($values['vote_name']), $this->_db->escapeString($values['vote_comment']), $values['vote_reference_id'], $this->_db->escapeString($values['vote_ip']), empty($values['vote_id']) ? 'NULL' : intval($values['vote_id']), $values['vote_created'], $values['vote_updated'], $values['vote_user_id']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['vote_updated'];
        $values['vote_updated'] = time();
        return sprintf('UPDATE %svoting_vote SET vote_entity_type = %s, vote_bundle_id = %d, vote_entity_id = %d, vote_value = %F, vote_tag = %s, vote_name = %s, vote_comment = %s, vote_reference_id = %d, vote_ip = %s, vote_updated = %d, vote_user_id = %d WHERE vote_id = %d AND vote_updated = %d', $this->_db->getResourcePrefix(), $this->_db->escapeString($values['vote_entity_type']), $values['vote_bundle_id'], $values['vote_entity_id'], $values['vote_value'], $this->_db->escapeString($values['vote_tag']), $this->_db->escapeString($values['vote_name']), $this->_db->escapeString($values['vote_comment']), $values['vote_reference_id'], $this->_db->escapeString($values['vote_ip']), $values['vote_updated'], $values['vote_user_id'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$svoting_vote WHERE vote_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['vote_updated'] = 'vote_updated=' . time();
        return sprintf('UPDATE %svoting_vote voting_vote SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(', ', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE voting_vote FROM %1$svoting_vote voting_vote WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$svoting_vote voting_vote WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}