<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Taxonomy_Model_Base_TermCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'term_name',
        'title' => 'term_title',
        'entityBundleName' => 'term_entity_bundle_name',
        'entityBundleType' => 'term_entity_bundle_type',
        'id' => 'term_id',
        'created' => 'term_created',
        'updated' => 'term_updated',
        'parent' => 'term_parent',
        'userId' => 'term_user_id',
    );
}