<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_BundleCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'bundle_name',
        'path' => 'bundle_path',
        'type' => 'bundle_type',
        'addon' => 'bundle_addon',
        'label' => 'bundle_label',
        'labelSingular' => 'bundle_label_singular',
        'info' => 'bundle_info',
        'system' => 'bundle_system',
        'entitytypeName' => 'bundle_entitytype_name',
        'id' => 'bundle_id',
        'created' => 'bundle_created',
        'updated' => 'bundle_updated',
    );
}