<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_FieldCacheCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'entityId' => 'fieldcache_entity_id',
        'fields' => 'fieldcache_fields',
        'entitytypeName' => 'fieldcache_entitytype_name',
        'id' => 'fieldcache_id',
        'created' => 'fieldcache_created',
        'updated' => 'fieldcache_updated',
        'bundleId' => 'fieldcache_bundle_id',
    );
}