<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_FieldConfigCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'fieldconfig_name',
        'type' => 'fieldconfig_type',
        'storage' => 'fieldconfig_storage',
        'system' => 'fieldconfig_system',
        'settings' => 'fieldconfig_settings',
        'property' => 'fieldconfig_property',
        'schema' => 'fieldconfig_schema',
        'entitytypeName' => 'fieldconfig_entitytype_name',
        'id' => 'fieldconfig_id',
        'created' => 'fieldconfig_created',
        'updated' => 'fieldconfig_updated',
        'bundleId' => 'fieldconfig_bundle_id',
    );
}