<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Entity_Model_Base_FieldCache extends SabaiFramework_Model_Entity
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('FieldCache', $model);
        $this->_vars = array('fieldcache_entity_id' => 0, 'fieldcache_fields' => null, 'fieldcache_entitytype_name' => null, 'fieldcache_id' => 0, 'fieldcache_created' => 0, 'fieldcache_updated' => 0, 'fieldcache_bundle_id' => 0);
    }

    public function __clone()
    {
        $this->_vars = array('fieldcache_id' => 0, 'fieldcache_created' => 0, 'fieldcache_updated' => 0) + $this->_vars;
    }

    public function __toString()
    {
        return 'FieldCache:' . $this->__get('id');
    }

    public function __get($name)
    {
        if ($name === 'entity_id')
            return $this->_vars['fieldcache_entity_id'];
        elseif ($name === 'fields')
            return $this->_vars['fieldcache_fields'];
        elseif ($name === 'entitytype_name')
            return $this->_vars['fieldcache_entitytype_name'];
        elseif ($name === 'id')
            return $this->_vars['fieldcache_id'];
        elseif ($name === 'created')
            return $this->_vars['fieldcache_created'];
        elseif ($name === 'updated')
            return $this->_vars['fieldcache_updated'];
        elseif ($name === 'bundle_id')
            return $this->_vars['fieldcache_bundle_id'];
        elseif ($name === 'Bundle')
            return $this->_fetchEntity('Bundle', 'bundle_id');
        else
            return $this->fetchObject($name);
    }

    public function __set($name, $value)
    {
        if ($name === 'entity_id')
            $this->_setVar('fieldcache_entity_id', $value);
        elseif ($name === 'fields')
            $this->_setVar('fieldcache_fields', $value);
        elseif ($name === 'entitytype_name')
            $this->_setVar('fieldcache_entitytype_name', $value);
        elseif ($name === 'id')
            $this->_setVar('fieldcache_id', $value);
        elseif ($name === 'bundle_id')
            $this->_assignEntityById('Bundle', $value, 'fieldcache_bundle_id');
        elseif ($name === 'Bundle') {
            $_value = is_array($value) ? $value[0] : $value;
            if (is_object($_value)) {
                $this->_assignEntity($_value, 'fieldcache_bundle_id');
            } else {
                $this->_assignEntityById('Bundle', $_value, 'fieldcache_bundle_id');
            }
        }
        else
            $this->assignObject($name, $value);
    }

    protected function _initVar($name, $value)
    {
        if ($name === 'fieldcache_entity_id')
            $this->_vars['fieldcache_entity_id'] = (int)$value;
        elseif ($name === 'fieldcache_fields')
            $this->_vars['fieldcache_fields'] = @unserialize($value);
        elseif ($name === 'fieldcache_id')
            $this->_vars['fieldcache_id'] = (int)$value;
        elseif ($name === 'fieldcache_created')
            $this->_vars['fieldcache_created'] = (int)$value;
        elseif ($name === 'fieldcache_updated')
            $this->_vars['fieldcache_updated'] = (int)$value;
        elseif ($name === 'fieldcache_bundle_id')
            $this->_vars['fieldcache_bundle_id'] = (int)$value;
        else
            $this->_vars[$name] = $value;
    }
}

abstract class Sabai_Addon_Entity_Model_Base_FieldCacheRepository extends SabaiFramework_Model_EntityRepository
{
    public function __construct(SabaiFramework_Model $model)
    {
        parent::__construct('FieldCache', $model);
    }

    public function fetchByBundle($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('fieldcache_bundle_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByBundle($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('Bundle', $id, $perpage, $sort, $order);
    }

    public function countByBundle($id)
    {
        return $this->_countByForeign('fieldcache_bundle_id', $id);
    }

    public function fetchByBundleAndCriteria($id, SabaiFramework_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('fieldcache_bundle_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByBundleAndCriteria($id, SabaiFramework_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('Bundle', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByBundleAndCriteria($id, SabaiFramework_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('fieldcache_bundle_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(SabaiFramework_DB_Rowset $rs)
    {
        return new Sabai_Addon_Entity_Model_Base_FieldCachesByRowset($rs, $this->_model->create('FieldCache'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Sabai_Addon_Entity_Model_Base_FieldCaches($this->_model, $entities);
    }
}

class Sabai_Addon_Entity_Model_Base_FieldCachesByRowset extends SabaiFramework_Model_EntityCollection_Rowset
{
    public function __construct(SabaiFramework_DB_Rowset $rs, Sabai_Addon_Entity_Model_FieldCache $emptyEntity, SabaiFramework_Model $model)
    {
        parent::__construct('FieldCaches', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(SabaiFramework_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Sabai_Addon_Entity_Model_Base_FieldCaches extends SabaiFramework_Model_EntityCollection_Array
{
    public function __construct(SabaiFramework_Model $model, array $entities = array())
    {
        parent::__construct($model, 'FieldCaches', $entities);
    }
}