<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_FieldCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'data' => 'field_data',
        'id' => 'field_id',
        'created' => 'field_created',
        'updated' => 'field_updated',
        'bundleId' => 'field_bundle_id',
        'fieldconfigId' => 'field_fieldconfig_id',
    );
}