<?php
/* This file has been auto-generated. Do not edit this file directly. */

abstract class Sabai_Addon_Entity_Model_Base_FieldCacheGateway extends SabaiFramework_Model_Gateway
{
    public function getName()
    {
        return 'entity_fieldcache';
    }

    public function getFields()
    {
        return array('fieldcache_entity_id' => SabaiFramework_Model::KEY_TYPE_INT, 'fieldcache_fields' => SabaiFramework_Model::KEY_TYPE_TEXT, 'fieldcache_entitytype_name' => SabaiFramework_Model::KEY_TYPE_VARCHAR, 'fieldcache_id' => SabaiFramework_Model::KEY_TYPE_INT, 'fieldcache_created' => SabaiFramework_Model::KEY_TYPE_INT, 'fieldcache_updated' => SabaiFramework_Model::KEY_TYPE_INT, 'fieldcache_bundle_id' => SabaiFramework_Model::KEY_TYPE_INT);
    }

    protected function _getIdFieldName()
    {
        return 'fieldcache_id';
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sentity_fieldcache WHERE fieldcache_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sentity_fieldcache WHERE fieldcache_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(', ', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$sentity_fieldcache entity_fieldcache WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery(&$values)
    {
        $values['fieldcache_created'] = time();
        $values['fieldcache_updated'] = 0;
        return sprintf('INSERT INTO %sentity_fieldcache(fieldcache_entity_id, fieldcache_fields, fieldcache_entitytype_name, fieldcache_id, fieldcache_created, fieldcache_updated, fieldcache_bundle_id) VALUES(%d, %s, %s, %s, %d, %d, %d)', $this->_db->getResourcePrefix(), $values['fieldcache_entity_id'], $this->_db->escapeString(serialize($values['fieldcache_fields'])), $this->_db->escapeString($values['fieldcache_entitytype_name']), empty($values['fieldcache_id']) ? 'NULL' : intval($values['fieldcache_id']), $values['fieldcache_created'], $values['fieldcache_updated'], $values['fieldcache_bundle_id']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['fieldcache_updated'];
        $values['fieldcache_updated'] = time();
        return sprintf('UPDATE %sentity_fieldcache SET fieldcache_entity_id = %d, fieldcache_fields = %s, fieldcache_entitytype_name = %s, fieldcache_updated = %d, fieldcache_bundle_id = %d WHERE fieldcache_id = %d AND fieldcache_updated = %d', $this->_db->getResourcePrefix(), $values['fieldcache_entity_id'], $this->_db->escapeString(serialize($values['fieldcache_fields'])), $this->_db->escapeString($values['fieldcache_entitytype_name']), $values['fieldcache_updated'], $values['fieldcache_bundle_id'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$sentity_fieldcache WHERE fieldcache_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['fieldcache_updated'] = 'fieldcache_updated=' . time();
        return sprintf('UPDATE %sentity_fieldcache entity_fieldcache SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(', ', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE entity_fieldcache FROM %1$sentity_fieldcache entity_fieldcache WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$sentity_fieldcache entity_fieldcache WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _afterInsert1($id, array $new)
    {
    }

    protected function _afterDelete1($id, array $old)
    {
    }

    protected function _afterUpdate1($id, array $new, array $old)
    {
    }

    protected function _afterInsert($id, array $new)
    {
        $this->_afterInsert1($id, $new);
    }

    protected function _afterUpdate($id, array $new, array $old)
    {
        $this->_afterUpdate1($id, $new, $old);
    }

    protected function _afterDelete($id, array $old)
    {
        $this->_afterDelete1($id, $old);
    }
}