<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Entity_Model_Base_FilterCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'filter_name',
        'type' => 'filter_type',
        'data' => 'filter_data',
        'id' => 'filter_id',
        'created' => 'filter_created',
        'updated' => 'filter_updated',
        'bundleId' => 'filter_bundle_id',
        'fieldId' => 'filter_field_id',
    );
}