<?php
/* This file has been auto-generated. Do not edit this file directly. */

class Sabai_Addon_Directory_Model_Base_ClaimCriteria extends SabaiFramework_Model_EntityCriteria
{
    protected $_keys = array(
        'name' => 'claim_name',
        'email' => 'claim_email',
        'comment' => 'claim_comment',
        'status' => 'claim_status',
        'type' => 'claim_type',
        'adminNote' => 'claim_admin_note',
        'entityId' => 'claim_entity_id',
        'entityBundleName' => 'claim_entity_bundle_name',
        'id' => 'claim_id',
        'created' => 'claim_created',
        'updated' => 'claim_updated',
        'userId' => 'claim_user_id',
    );
}